CREATE TABLE COUNTRY (
	COUNTRY_ID SERIAL PRIMARY KEY,
	COUNTRY_NAME TEXT UNIQUE NOT NULL
);

CREATE TABLE AUTHOR (
	AUTHOR_ID INT PRIMARY KEY,
	AUTHOR_NAME TEXT NOT NULL,
	AUTHOR_ORIGINAL_NAME TEXT NOT NULL,
	UNIQUE_WORDS_COUNT INT,
	WORDS_PER_SENTENCE_COUNT INT,
	LONGEST_SENTENSE_WORDS_COUNT INT,
	LAST_DATE_OF_UPDATE DATE,
	COUNTRY_ID INT REFERENCES COUNTRY (COUNTRY_ID)
);

CREATE TABLE TEXT(
	TEXT_ID INT PRIMARY KEY,
	TITLE TEXT NOT NULL,
	SUBTITLE TEXT,
	YEAR INT,
	UNIQUE_WORDS_COUNT INT,
	LAST_DATE_OF_UPDATE DATE,
	AUTHOR_ID INT REFERENCES AUTHOR (AUTHOR_ID)
);