-- Database: EKATTE

CREATE TABLE SETTLEMENT_TYPE (
    SETTLEMENT_TYPE_ID INTEGER PRIMARY KEY,
    SETTLEMENT_TYPE_DESCRIPTION CHAR(4)
        CHECK (SETTLEMENT_TYPE_DESCRIPTION IN ('гр.', 'с.', 'ман.'))
        NOT NULL
);

CREATE TABLE ALTITUDE (
    ALTITUDE_ID INTEGER PRIMARY KEY,
    ALTITUDE_DESCRIPTION TEXT NOT NULL
);

CREATE TABLE REGION (
    REGION_ID CHAR(3) PRIMARY KEY,
    NAME TEXT NOT NULL,
    TRANSLITERATION TEXT NOT NULL,
    NUTS3_ID CHAR(5) UNIQUE NOT NULL,
	LAST_CHANGED_ON TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE MUNICIPALITY (
    MUNICIPALITY_ID CHAR(5) PRIMARY KEY,
    NAME TEXT NOT NULL,
    TRANSLITERATION TEXT NOT NULL,
	LAST_CHANGED_ON TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    REGION_ID CHAR(3) NOT NULL
        REFERENCES REGION (REGION_ID)
);

CREATE TABLE MAYORALITY (
    MAYORALITY_ID CHAR(8) PRIMARY KEY,
    NAME TEXT NOT NULL,
    TRANSLITERATION TEXT NOT NULL,
	LAST_CHANGED_ON TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MUNICIPALITY_ID CHAR(5) NOT NULL
        REFERENCES MUNICIPALITY (MUNICIPALITY_ID)
);

CREATE TABLE SETTLEMENT (
    EKATTE CHAR(5) PRIMARY KEY,
    NAME TEXT NOT NULL,
    TRANSLITERATION TEXT NOT NULL,
    SETTLEMENT_CATEGORY INTEGER NOT NULL,
	LAST_CHANGED_ON TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ALTITUDE_ID INTEGER NOT NULL
        REFERENCES ALTITUDE (ALTITUDE_ID),
    SETTLEMENT_TYPE_ID INTEGER NOT NULL
        REFERENCES SETTLEMENT_TYPE (SETTLEMENT_TYPE_ID),
    MAYORALITY_ID CHAR(8)
        REFERENCES MAYORALITY (MAYORALITY_ID),
    MUNICIPALITY_ID CHAR(5) NOT NULL
        REFERENCES MUNICIPALITY (MUNICIPALITY_ID)
);

-- Center tables
CREATE TABLE REGION_CENTER (
    REGION_ID CHAR(3) PRIMARY KEY
        REFERENCES REGION (REGION_ID),
    SETTLEMENT_EKATTE CHAR(5) UNIQUE NOT NULL
        REFERENCES SETTLEMENT (EKATTE)
);

CREATE TABLE MUNICIPALITY_CENTER (
    MUNICIPALITY_ID CHAR(5) PRIMARY KEY
        REFERENCES MUNICIPALITY (MUNICIPALITY_ID),
    SETTLEMENT_EKATTE CHAR(5) UNIQUE NOT NULL
        REFERENCES SETTLEMENT (EKATTE)
);

CREATE TABLE MAYORALITY_CENTER (
    MAYORALITY_ID CHAR(8) PRIMARY KEY
        REFERENCES MAYORALITY (MAYORALITY_ID),
    SETTLEMENT_EKATTE CHAR(5) UNIQUE NOT NULL
        REFERENCES SETTLEMENT (EKATTE)
);

-- Indexes
CREATE INDEX idx_settlement_altitude_id ON settlement (altitude_id);
CREATE INDEX idx_settlement_settlement_type_id ON settlement (settlement_type_id);
CREATE INDEX idx_settlement_mayorality_id ON settlement (mayorality_id);
CREATE INDEX idx_settlement_municipality_id ON settlement (municipality_id);
CREATE INDEX idx_municipality_region_id ON municipality (region_id);
CREATE INDEX idx_mayorality_municipality_id ON mayorality (municipality_id);
CREATE INDEX idx_settlement_name ON SETTLEMENT (NAME);
CREATE INDEX idx_municipality_name ON MUNICIPALITY (NAME);
CREATE INDEX idx_mayorality_name ON MAYORALITY (NAME);
