BEGIN;

CREATE OR REPLACE FUNCTION update_last_changed_column()
RETURNS TRIGGER AS $$
BEGIN
   NEW."last_changed_on" = CURRENT_TIMESTAMP;
   RETURN NEW;
END;
$$ language 'plpgsql';

ALTER TABLE REGION ADD COLUMN "last_changed_on" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
CREATE TRIGGER tr_region_last_changed BEFORE UPDATE ON REGION 
FOR EACH ROW EXECUTE FUNCTION update_last_changed_column();

ALTER TABLE MUNICIPALITY ADD COLUMN "last_changed_on" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
CREATE TRIGGER tr_municipality_last_changed BEFORE UPDATE ON MUNICIPALITY 
FOR EACH ROW EXECUTE FUNCTION update_last_changed_column();

ALTER TABLE MAYORALITY ADD COLUMN "last_changed_on" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
CREATE TRIGGER tr_mayorality_last_changed BEFORE UPDATE ON MAYORALITY 
FOR EACH ROW EXECUTE FUNCTION update_last_changed_column();

ALTER TABLE SETTLEMENT ADD COLUMN "last_changed_on" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
CREATE TRIGGER tr_settlement_last_changed BEFORE UPDATE ON SETTLEMENT 
FOR EACH ROW EXECUTE FUNCTION update_last_changed_column();

COMMIT;